### PR TITLE
Fix when sensor-simulator is not the first service added

### PR DESCRIPTION
**Pull request by garydblack**
Sensor simulator wasn't getting user_options correctly unless it was the first service added because it was hardwired to assume service_configs element [0] was the correct one.  Now it checks each service_configs id for the proper one for sensor simulator and gets the user_options corresponding to that.  This is github issue #1294.

---
This change is [Reviewable](https://reviewable.io/reviews/gridappsd/gridappsd-sensor-simulator/15)

### CODE REVIEW

**Comment by poorva1209** [comment]
@garydblack This looks like a lot of change. Did you do a git pull and merge with the latest before making changes?

**Comment by poorva1209** [comment]
@garydblack Oh, I know what you did. You made changes directly in the develop branch. For future, fork the repository and then create a pull request from your fork to main develop branch. Develop branch is merged into master only when a release is done. Developers work on their own forks.

**Comment by poorva1209** [comment]
I saw the changes in your commit to develop branch. It looks good to me. I will close this pull request and create an issue on github board for Tonya to merge this with master during release.

**Comment by garydblack** [comment]
Thanks Poorva.  Thanks for letting me know how it is done.  I didn't know that's how the develop branch was used.  I have no problem waiting for this until the release merge.  Just wanted to get it taken care of.  In the future I'll fork a new branch instead of committing changes to develop.

**Pull request closed without merging**
